# LPC Configuration
# Please read the https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta before you set up.
#
# Placeholders:
# {message} - the chat message
# {name} - the player's name
# {displayname} - the player's display name / nickname
# {world} - the world name of the player's current world
# {prefix} - the player's highest priority prefix
# {suffix} - the player's highest priority suffix
# {prefixes} - the player's prefixes sorted by the highest priority
# {suffixes} - the player's suffixes sorted by the highest priority
# {username-color} - the player's or the group's username color
# {message-color} - the player's or the group's message color

# WARNING: Prefixes, Suffixes, message-color etc. needs to be Minimessage Colorcodes and not Legacy!

# To reload the configuration, run '/lpc reload' command. Make sure you have the 'lpc.reload' permission assigned.
# More information can be found at the Github Wiki.
chat-format: "{prefix}{name}<dark_gray> »<reset> {message}"

# Set the format per group.
# Note: Option for more advanced users. Remove comments to run.
group-formats:
#  default: "[default] {name}<dark_gray> »<reset> {message}"
#  admin: "[admin] {name}<dark_gray> »<reset> {message}"

# Set the format per track
# Note: Group formatting takes priority over track formatting, ensure user isn't in a group with corresponding format to apply track format
track-formats:
#  staff_track: "[staff] {name}<dark_gray> »<reset> {message}"
#  donator_track: "{donator_rank} {name}<dark_gray> »<reset> {message}"

# Should the [item] placeholder be enabled
use-item-placeholder: true

# Editing Reload-message
reload-message: "<green>Reloaded LPC Configuration!"